export const ADD_PRODUCT_TO_CAR = "ADD_PRODUCT_TO_CAR";
export const REMOVE_PRODUCT_TO_CAR = "REMOVE_PRODUCT_TO_CAR";
export const REMOVE_CLIENT = "REMOVE_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const GET_CLIENTS = "GET_CLIENTS";
